// <auto-generated />
using System;
using GeneradorDeExamenes.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneradorDeExamenes.Entidades.Migrations
{
    [DbContext(typeof(ExamenIaContext))]
    partial class ExamenIaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneradorDeExamenes.Entidades.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categoria__19093A0B4B7734FF");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("GeneradorDeExamenes.Entidades.Examan", b =>
                {
                    b.Property<int>("IdExamen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExamen"));

                    b.Property<int?>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.HasKey("IdExamen")
                        .HasName("PK__Examen__0E8DC9BE4AB36D21");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Examen");
                });

            modelBuilder.Entity("GeneradorDeExamenes.Entidades.Preguntum", b =>
                {
                    b.Property<int>("IdPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPregunta"));

                    b.Property<int>("IdExamen")
                        .HasColumnType("int");

                    b.Property<string>("PreguntaTexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaCorrecta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespuestaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPregunta")
                        .HasName("PK__Pregunta__754EC09E6A00DE24");

                    b.HasIndex("IdExamen");

                    b.ToTable("Pregunta");
                });

            modelBuilder.Entity("GeneradorDeExamenes.Entidades.Examan", b =>
                {
                    b.HasOne("GeneradorDeExamenes.Entidades.Categoria", "Categoria")
                        .WithMany("Examenes")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK__Examen__IdCatego__5EBF139D");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GeneradorDeExamenes.Entidades.Preguntum", b =>
                {
                    b.HasOne("GeneradorDeExamenes.Entidades.Examan", "IdExamenNavigation")
                        .WithMany("Pregunta")
                        .HasForeignKey("IdExamen")
                        .IsRequired()
                        .HasConstraintName("FK__Pregunta__IdExam__5FB337D6");

                    b.Navigation("IdExamenNavigation");
                });

            modelBuilder.Entity("GeneradorDeExamenes.Entidades.Categoria", b =>
                {
                    b.Navigation("Examenes");
                });

            modelBuilder.Entity("GeneradorDeExamenes.Entidades.Examan", b =>
                {
                    b.Navigation("Pregunta");
                });
#pragma warning restore 612, 618
        }
    }
}
